---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: centos7
    excludes:
      - centos-6
    verifier:
      inspec_tests:
          - name: centos7
            path: test/integration/centos7/inspec
    run_list:
      - recipe[stig]
    attributes: {
      "auditd" : {
        "ruleset" : "stig"
      }
    }

  - name: centos6
    excludes:
      - centos-7
    verifier:
      inspec_tests:
          - name: centos6
            path: test/integration/centos6/inspec
    run_list:
      - recipe[stig]
    attributes: {
      "auditd" : {
        "ruleset" : "stig"
      }
    }
